baseURL= 'https://yeahman.pages.dev'
languageCode = 'en-us'
title = 'sandworm.cc'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 6

[languages]
[languages.en]
title = "sandworm"
weight = 1
contentDir = "content/english" 
[languages.tr]
title = "sandworm 🇹🇷"
weight = 2
contentDir = "content/turkish"

[params]
text_color = "black"
author = "birbsophone"
favicon = "/images/logo.png"
site_logo = ""
background_color_class = "bg-black"
recent_posts_number = 6

[markup.goldmark.renderer]
unsafe = true

[params.ananke.social.follow]
networks = [
  "github"
]

[params.ananke.social.github]
username = "birbsophone"
profilelink = "https://github.com/birbsophone/blog"
